def SERVICE_GROUP = ""
def SERVICE_NAME = ""
def IMAGE_NAME = "${SERVICE_GROUP}-${SERVICE_NAME}"
def REPOSITORY_URL = ""
def REPOSITORY_SECRET = ""
def SLACK_TOKEN_DEV = ""
def SLACK_TOKEN_DQA = ""

@Library("bespin-pipeline-library")
def butler = new com.bespin.devops.JenkinsPipeline()
def label = "maven-jdk8"

properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "30"))
])
podTemplate {
  node(label) {
    stage("Prepare") {
      container("builder") {
        butler.prepare(IMAGE_NAME)
      }
    }
    stage("Checkout") {
      container("builder") {
        try {
          if (REPOSITORY_SECRET) {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME, credentialsId: REPOSITORY_SECRET)
          } else {
            git(url: REPOSITORY_URL, branch: BRANCH_NAME)
          }
        } catch (e) {
          butler.failure(SLACK_TOKEN_DEV, "Checkout")
          throw e
        }

        butler.scan("java")
      }
    }
    stage("Build") {
      container("maven") {
        try {
          butler.mvn_build()
          butler.success(SLACK_TOKEN_DEV, "Build")
        } catch (e) {
          butler.failure(SLACK_TOKEN_DEV, "Build")
          throw e
        }
      }
    }
    stage("Tests") {
      container("maven") {
        try {
          butler.mvn_test()
        } catch (e) {
          butler.failure(SLACK_TOKEN_DEV, "Tests")
          throw e
        }
      }
    }
    stage("Code Analysis") {
      container("maven") {
        try {
          butler.mvn_sonar()
        } catch (e) {
          butler.failure(SLACK_TOKEN_DEV, "Code Analysis")
          throw e
        }
      }
    }
    if (BRANCH_NAME == "master") {
      stage("Deploy Nexus") {
        container("maven") {
          try {
            butler.mvn_deploy()
            butler.success(SLACK_TOKEN_DEV, "Deploy")
          } catch (e) {
            butler.failure(SLACK_TOKEN_DEV, "Deploy")
            throw e
          }
        }
      }
    }
  }
}
